export const generalKnowledge = {
  vi: {
    overview: `Địa đạo Củ Chi khởi nguồn năm 1948 tại Tân Phú Trung và Phước Vĩnh An, phát triển vượt bậc từ 1961 làm căn cứ Khu ủy và Quân khu Sài Gòn - Gia Định. Tổng chiều dài 250 km (trên 200 km ở một số tư liệu) kết nối 500 km hào nổi, điểm cuối Đường mòn Hồ Chí Minh, cách trung tâm TP.HCM 70 km Tây-Bắc. Cấu trúc 3 tầng: Tầng 1 (~3m) chịu pháo và xe tăng; Tầng 2 (5-8m) chứa bếp Hoàng Cầm, bệnh xá, kho; Tầng 3 (8-12m) là hầm chỉ huy với ngách thoát hiểm ra sông Sài Gòn. Đất sét pha đá ong (laterit) tự hóa cứng như đá, tuyệt đối không dùng bê tông chống đỡ. Xếp hạng Di tích Quốc gia Đặc biệt theo Quyết định 2367/QĐ-TTg (2015), quản lý 120,62 ha rừng phòng hộ, hoàn tất Giai đoạn 1 năm 2022 và dự kiến trình UNESCO công nhận Di sản Thế giới vào năm 2027. Di tích mở cửa 7h-17h hàng ngày (vé 35k/70k), 6 tháng đầu năm 2024 đón 650.000 lượt khách (+78,6%) với điểm nhấn Tour đêm "Trăng chiến khu".`,
    sacred: `Đền Tưởng niệm Liệt sĩ Bến Dược khắc ghi danh tính 44.357 anh hùng liệt sĩ trên 632 phiến đá hoa cương — con số thiêng liêng từ hồ sơ Bộ Quốc phòng. Tên Củ Chi lấy từ loài cây Strychnos nux-vomica bản địa. Đời sống kháng chiến 1950-1951 là một "xã hội Nghiêu Thuấn" kiểu mẫu theo ghi nhận của đồng chí Võ Văn Kiệt. Đêm Giáng sinh 1966 ghi dấu sự đối lập lịch sử: nghệ sĩ Phạm Sáng diễn kịch ngầm dưới đèn dầu trong khi Bob Hope tấu hài cho quân Mỹ trên mặt đất. Đối phương lập đội "Lính chuột chũi" (Tunnel Rats dưới 1m65, súng .38 giảm thanh) nhưng đều bất lực trước hai trận càn Crimp (1966) và Cedar Falls (1967). Nhóm ĐH Văn Lang đề xuất Công nghệ đất đông cứng (Ground Freezing) và Bảo tàng đất nén (Rammed Earth) bảo tồn bền vững di sản.`
  },
  en: {
    overview: `Cu Chi Tunnels originated in 1948 in Tan Phu Trung and Phuoc Vinh An, expanding from 1961 as the base for Saigon - Gia Dinh Regional Command. Spanning 250 km (over 200 km in some archives) connected to 500 km of trenches, it sits 70 km NW of HCMC at the terminus of the Ho Chi Minh Trail. 3 levels: Level 1 (~3m) anti-tank & artillery; Level 2 (5-8m) hospital, Hoang Cam stove, supply depots; Level 3 (8-12m) command bunker with emergency escape to Saigon River. Built in laterite clay that hardens like rock without concrete. Classified Special National Relic in 2015 (Decision 2367/QD-TTg) managing 120.62 hectares of protected forest, Phase 1 UNESCO submission completed in 2022, targeting UNESCO World Heritage inscription by 2027. Open daily 7 AM - 5 PM (35k/70k VND), welcoming 650,000 visitors in H1 2024 (+78.6%) with the acclaimed "War Zone Moonlight" Night Tour.`,
    sacred: `Ben Duoc Memorial Temple commemorates 44,357 fallen heroes across 632 granite slabs verified by Defense Ministry records. The name Cu Chi derives from the native toxic tree Strychnos nux-vomica L. Wartime life in 1950-1951 reflected an ideal harmonious society described by leader Vo Van Kiet. Christmas Eve 1966 highlighted profound contrast: artist Pham Sang staged underground plays under oil lamps while Bob Hope entertained US troops above. US forces deployed "Tunnel Rats" (under 165 cm, silenced .38 revolvers) yet failed across Operations Crimp (1966) and Cedar Falls (1967). Modern non-invasive preservation proposals by Van Lang University feature Ground Freezing Technology and a Rammed Earth Museum near Saigon River.`
  }
};
